// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ShaderTools.Editor.VisualStudio
{
    static class Vsix
    {
        public const string Id = "05002c97-2be5-4ccb-8d07-751f755d10ff";
        public const string Name = "GLSL Tools for Visual Studio";
        public const string Description = @"Enhanced support for editing GLSL in Visual Studio";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Shlomi Steinberg";
        public const string Tags = "GLSL";
    }
}
